# Logistic regression 

โดยแนะนำเทคนิดนี้จะเป็นการเดาแบบ เป็นสิ่งนี้หรือสิ่งนั้น เช่น ใช่ หรือ ไม่ใช่ (classification)

โดยต่างจากพวก regression ธรรมโดยการเดา $W,C$ แล้วทำการอัปเดทด้วย gradient  decent

โดยจะมีการใช้ entropy

# Entropy คืออะไร

เป็นการวัดความไม่แน่นอน (uncertainty) ของระบบหรือความน่าจะเป็นที่จะเกิดสิ่งต่าง ๆ

![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTm4RFmvGvS372S4uliQO0_p1u7j208ndeZWQ&s)

วัดความไม่แน่นอน คือ? จากตัวอย่างในรูปจะเห็นแกน x หมายถึงการเดา/โอกาส ถ้าเดาได้โอกาส  1 คือ แกน y คือ 0 ความไม่แน่นอน0 

ความไม่แน่นอน0 ก็คือ แน่นอนหรือมั้นใจ 100% อะไรประมาณนั้น

แล้วคุณจะเห็นตรง 0.5 แกน x ซี่ง ความไม่แน่นอนคือ 1 หมายถึง ไม่มีความมั้นใจเลยว่าจะออกมาเป็น 0หรือ 1 เลย

นั้นคือความหมายของ entropy

ในเรื่องนี้เราจะใช้ Binary Cross-Entropy Loss

$Loss = -\frac{1}{N} \sum_{i=1}^{N} \left[ y_i \cdot \log(\hat{y}_i) + (1 - y_i) \cdot \log(1 - \hat{y}_i) \right]$

$y_{i}$= ค่าจริง (0 หรือ 1)

$\hat{y_{i}}$= ค่าที่โมเดลทำนาย (อยู่ในช่วง 0 ถึง 1)

log ฐาน e นะครับ

# แล้ว regression คือเกี่ยวอะไร

เราจะนำ sigmoid คือ activate function หรือ sigmoid มีอีกชื่อ logistic

นี่คือที่มา logistic

เอ้าหัวข้อ regression แล้วทำไมมาบอก logistic 

ซึ่ง สมการ logistic หรือ sigmoid

คือ

$\sigma(z) = \frac{1}{1 + e^{-z}}$

In [8]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

ตรง z คือสมการ regression คือ $w_0+w_1x_1+w_2x_2+w_3x_3+...+w_nx_n$

และสามารถของเรื่องนี้คือ $\hat{y}=\sigma(w_0+w_1x_1+w_2x_2+w_3x_3+...+w_nx_n)$

หรือ

$\hat{y}=\frac{1}{1 + e^{-(w_0+w_1x_1+w_2x_2+w_3x_3+...+w_nx_n)}}$

ซึ่ง $\hat{y} = \frac{1}{1 + e^{-z}}$ เมื่อ z=$w_0+w_1x_1+w_2x_2+w_3x_3+...+w_nx_n$

# sigmoid ใช้ทำไม

![image](https://miro.medium.com/v2/resize:fit:1033/0*D5do3xhv5ulF50w2.png)

จากเส้นจะเห็นได้ว่า เข้าใกล้อะไรเดาได้อันนั้น

In [9]:
def predict(X, weights):
    z = np.dot(X, weights)
    return sigmoid(z)

# Binary Cross-Entropy Loss

ที่มาเราต้องมีความรู้เรื่องความน่าจะเป็นก่อน

ความน่าจะเป็น ของ แบนูลี (Bernoulli)

P(x=1) = p 

P(x=0) = q = 1-p

เขียนแบบ Probability mass function(PMF) 
$f(k|p) =\begin{cases}
p & ;if k=1 \\
q = 1-p & ;if k=0\\
\end{cases}$

จากสมการด้านบนเราสามารถ บอกได้ว่า

$f(k; p) = p^k (1 - p)^{1 - k} \quad \text{for } k \in \{0, 1\}$

ใช้  Likelihood

$L(\hat{y}) = \prod_{i=1}^{n} \hat{y}_i^{y_i} (1 - \hat{y}_i)^{1 - y_i}$

เพื่อหลีกเลี่ยงการคูณจำนวนมาก (ซึ่งทำให้ค่ากลายเป็น 0 หรือ underflow),  

Log-Likelihood

$
\log L(\hat{y}) = \sum_{i=1}^{n} \left[ y_i \log(\hat{y}_i) + (1 - y_i) \log(1 - \hat{y}_i) \right]
$

เราให้ $P(y_i|x;\hat{y_i})$ เมื่อ $y_i$ มีค่าช่วง {0,1}

In [10]:
def loss(y, y_pred):
    return -np.mean(y * np.log(y_pred + 1e-8) + (1 - y) * np.log(1 - y_pred + 1e-8))

# ดาต้า

วันเรียน,เวลานอน

Label: สอบผ่านหรือไม่ (1=ผ่าน, 0=ไม่ผ่าน)

In [11]:
import numpy as np

x = np.array([
    [2, 1],
    [1, 0],
    [3, 1],
    [2, 0],
    [3, 0],
    [1, 1],
    [4, 1],
    [3, 1],
])

# Label: สอบผ่านหรือไม่ (1=ผ่าน, 0=ไม่ผ่าน)
y = np.array([1, 0, 1, 0, 0, 0, 1, 1])

ทำการเพิ่ม bias ตรง w_0

In [12]:
X = np.hstack([np.ones((x.shape[0], 1)), x])
X

array([[1., 2., 1.],
       [1., 1., 0.],
       [1., 3., 1.],
       [1., 2., 0.],
       [1., 3., 0.],
       [1., 1., 1.],
       [1., 4., 1.],
       [1., 3., 1.]])

# train 

จะเห็นว่าผมได้ทำการ gradient = X.T @ (y_pred - y) / y.size

ได้ทำการ diff เทียบ w

ทำยังไง ตรง$Loss = -\frac{1}{N} \sum_{i=1}^{N} \left[ y_i \cdot \log(\hat{y}_i) + (1 - y_i) \cdot \log(1 - \hat{y}_i) \right]$

แล้ว $\hat{y_i} = \sigma(z_i) หรือ  \sigma(\mathbf{w}^T \mathbf{x}^{(i)})$

จะdiff ให้ดู

คิดว่า $\frac{1}{N} \sum_{i=1}^{N} l_i$

คือผมให้ $l_i=-\left[ y_i \cdot \log(\hat{y}_i) + (1 - y_i) \cdot \log(1 - \hat{y}_i) \right]$ จะได้มองง่าย

$\frac{dl_i}{d\hat{y_i}} = \frac{y_{(i)}}{\hat{y}_{(i)}} + \frac{1 - y_{(i)}}{1 - \hat{y}_{(i)}}$

ยังไง $\frac{dlog(x)}{dx} = \frac{1}{x}$

แสดงว่า $\frac{dy_i*log(\hat{y_i})}{d\hat(y_i)} = y_i * \frac{dlog(\hat{y_i})}{d\hat{y_i}}$

จะได้ $y_i*\frac{1}{\hat{y_i}}$ = $\frac{y_i}{\hat{y_i}}$ นั้นเอง

ทำให้ $\frac{dl_i}{d\hat{y_i}} = -\frac{y_{(i)}}{\hat{y}_{(i)}} + \frac{1 - y_{(i)}}{1 - \hat{y}_{(i)}}$

ซึ่งเราต้อง diff ถึง w

ต่อไปคือ 

ทำให้ 

diff by $z_i$เมื่อ $\hat{y_i} = \sigma(z_i) $

$\frac{d\hat{y_i}}{dz_i} = \frac{d}{dz_i}\frac{1}{1 + e^{-z}}= \frac{d}{dz_i}(1+e^{-z_I})^{-1}$ =

$-1 * (1+e^{-z_i})^{-2} * \frac{d}{dz_i} (1+e^{-z_i})$=

$-1 * (1+e^{-z_i})^{-2} * (-e^{-z_i})= \frac{e^{-z_i}}{(1+e^{-z_i})^{2}}$

เนื่องจาก$ \sigma(z_i) = \frac{1}{1 + e^{-z}}$ แปลงรูป $\frac{e^{-z_i}}{(1+e^{-z_i})^{2}}$

ถ้า$\sigma(z_i)^{2} = \frac{1}{(1 + e^{-z})^2}$

ถ้า$\sigma(z_i)^{2} *e^{-z_i} = \frac{e^{-z_i}}{(1 + e^{-z})^2}$

ซึ่งอันนี้ก็ได้รูปอย่างง่าย $\sigma(z_i)^{2} *e^{-z_i} $


รูปอย่างง่าย กว่าคือ

= σ(z)(1−σ(z))

มาจาก 1−σ(z) = $1-\frac{1}{(1 + e^{-z})}$

ทำเศษส่วนให้เท่ากัน $\frac{1*(1+e^{-z})}{1+e^{-z}}-\frac{1}{(1 + e^{-z})} = \frac{1+e^{-z}-1}{1 + e^{-z}} = \frac{e^{-z}}{1+e^{-z}}$

ทั้งนั้ง 1−σ(z) = $\frac{e^{-z}}{1+e^{-z}}$

σ(z)(1−σ(z)) $ = \frac{e^{-z_i}}{(1 + e^{-z})^2}$

dff w_i เมือz =wTxi


$\frac{dz_i}{dw_i} = \frac{dw^Tx_i}{dw_i} = x_i$

จากกดลูกโซ่

ให้ $\frac{dl_i}{dw_i} =  \frac{dl_i}{d\hat{y_i}} *  \frac{d\hat{y_i}}{dz_i} * \frac{dz_i}{dw_i}$

จะได้ $-\frac{y_{(i)}}{\hat{y}_{(i)}} + \frac{1 - y_{(i)}}{1 - \hat{y}_{(i)}} * σ(z)(1−σ(z)) * x_i$

เนื่องจาก $\hat{y_i}=σ(z)$

= $-\frac{y_{(i)}}{\hat{y}_{(i)}} + \frac{1 - y_{(i)}}{1 - \hat{y}_{(i)}} * \hat{y_i}(1−\hat{y_i}) * x_i$

รูปอย่างง่าย

dl_i= $(\hat{y_i}-y_i)*x_i$

ได้ grad

$\frac{1}{N} \sum_{i=1}^{N} (\hat{y_i}-y_i)*x_i $

In [13]:
def train(X, y, lr=0.1, epochs=1000):
    weights = np.zeros(X.shape[1])
    for epoch in range(epochs):
        z = np.dot(X, weights)
        y_pred = sigmoid(z)

        gradient = X.T @ (y_pred - y) / y.size
        weights -= lr * gradient

        if epoch % 100 == 0:
            print(f"Epoch {epoch}: Loss = {loss(y, y_pred):.4f}")

    return weights

def evaluate(X, y, weights):
    X = np.hstack([np.ones((X.shape[0], 1)), X])
    y_pred = predict(X, weights)
    predictions = (y_pred >= 0.5).astype(int)
    accuracy = np.mean(predictions == y)
    print("Accuracy:", accuracy)
    return predictions


# train 

In [14]:
weights = train(X,y)

Epoch 0: Loss = 0.6931
Epoch 100: Loss = 0.4860
Epoch 200: Loss = 0.3897
Epoch 300: Loss = 0.3313
Epoch 400: Loss = 0.2918
Epoch 500: Loss = 0.2630
Epoch 600: Loss = 0.2409
Epoch 700: Loss = 0.2233
Epoch 800: Loss = 0.2088
Epoch 900: Loss = 0.1966


ค่าที่ได้ มีสามตัวเพราะดาต้าเรา ค่าฺbias,เรียน,นอน

In [15]:
weights

array([-4.96922711,  1.2430915 ,  3.39444434])

$w_0+w_1x_1+w_2x_2$

 x =ค่าฺbias,เรียน,นอน

ลอง predict โดยคิดว่า bias 1  เรียน 2 นอน 0 

In [ ]:
y_pred = predict(np.array([[1,2,0]]), weights)


Epoch 0: Loss = 0.6931
Epoch 100: Loss = 0.4860
Epoch 200: Loss = 0.3897
Epoch 300: Loss = 0.3313
Epoch 400: Loss = 0.2918
Epoch 500: Loss = 0.2630
Epoch 600: Loss = 0.2409
Epoch 700: Loss = 0.2233
Epoch 800: Loss = 0.2088
Epoch 900: Loss = 0.1966


และค่าที่ได้จาก  predictions มากกว่า 0.5 คือ ตีเป็น 1 คือสอบผ่าน ถ้าน้อยกว่า 0.5 ให้ 0 คือสอบไม่ผ่าน

In [28]:
y_pred

array([0.07705543])

In [29]:
predictions = (y_pred >= 0.5).astype(int)
predictions

array([0])

สรุปได้

ลอง bias 1 เรียน 3 นอน 1  

In [25]:
y_pred = predict(np.array([[1,3,1]]), weights)
predictions = (y_pred >= 0.5).astype(int)
predictions

array([1])

สรุปก็ตรงถามที่เทรนเลย